### ISSUE TITLE
Missing elevation

### ISSUE THREAD

**Issue by mdekauwe** [aukkola/FLUXNET2015_processing#22]
Not essential for the LSM stuff, but might be nice to add it back to the NC file?

I wrote something here

https://github.com/mdekauwe/FLUXNET2015_data/blob/master/src/get_site_info.py

**Comment by naught101** [comment]
I think this is defunct now. We now have all of the available metadata information from ORNL/Fluxnet (including elevation where available) in the data/Site_metadata.CSV, and there is a scraper to update that file available (`update_csv_from_web()`).

**Comment by aukkola** [comment]
Some of the sites are missing elevation and it is necessary for synthesising air pressure for La Thuile. Obviously Martin's code would need to be rewritten in R. Alternatively I can obtain the site elevation from a local GTOPO file as I've already done for some sites, but any new sites with missing elev would of course not be automatically updated this way.

**Comment by naught101** [comment]
Any new sites will not be in La Thuile though, and so would (hopefully) include pressure, right? I would just add elevation for the missing sites where possible for now. I you think it's worth it, I'm happy to re-write something like Martin's script in R.

**Comment by aukkola** [comment]
Added elevation to site metadata based on GTOPO30 dataset. One or two sites still missing elevation (one of which is in Antarctica)
