### ISSUE TITLE
metadata of US-Wi9 site

### ISSUE THREAD

**Issue by Mbnl1197** [aukkola/FLUXNET2015_processing#68]
The following error occurred while processing the US-Wi9 site.Can't this site handle it?

`Loading metadata for US-Wi9 from csv_data cache ()
New metadata for Exclude has different values! Overwriting.
  old: FALSE, new: WAAR
Trying to load new_metadata for US-Wi9 from Fluxdata.org (http://sites.fluxdata.org/US-Wi9/)
No data available at http://sites.fluxdata.org/US-Wi9/ (NULL)
US-Wi9 not found in table at https://fluxnet.ornl.gov/site_status
Missing metadata for site US-Wi9:
   TowerHeight, CanopyHeight, SoilType, Disturbance
Error in !is.null(site_info$Exclude) & site_info$Exclude : 
  operations are possible only for numeric, logical or complex types`

**Comment by jsta** [comment]
I think this is because the code tries to scrape table information from https://fluxnet.ornl.gov/site_status which for me doesn't resolve to a table.

This works for me however.

```r
get_site_metadata("US-Wi9", use_csv=TRUE)
```
